- name: "Install Coral USB Accelerator dependencies on Raspberry Pi"
  hosts: "rpi_vision"
  gather_facts: false
  vars:
    rpi_vision_dir: "{{ RPI_VISION_DIR | default('/home/pi/rpi-vision') }}"
  tasks:
    - name: "Download Edge TPU API"
      get_url:
        url: https://dl.google.com/coral/edgetpu_api/edgetpu_api_latest.tar.gz
        dest: ~/edgetpu_api.tar.gz
    - name: "Untar Edge TPU API"
      unarchive:
        dest: ~/
        remote_src: True
        src: ~/edgetpu_api.tar.gz
    - name: "Install Edge TPU API"
      shell: . {{rpi_vision_dir}}/.venv/bin/activate && yes no | \
        SCRIPT_DIR=/home/pi/edgetpu_api \
        /bin/bash /home/pi/rpi-vision/tools/edgetpu_api_install.sh
        
